### PR TITLE
[Grappler] Add Concat+Cast fusion

### PR DESCRIPTION
**Pull request by aalbersk**
For the BF16 graph, we usually find a concat+cast pattern from the feature column to DNN part.
The optimization is for concat(FP32 -> FP32) + cast(FP32 > BF16) and concat(BF16 -> BF16) + cast(BF16 > FP32) to fuse one op.

### CODE REVIEW

**Comment by changqi1** [comment]
@aalbersk  Please add api_def, like **FusedL2Normalize** in tensorflow/core/api_def/base_api/api_def_FusedL2Normalize.pbtxt from https://github.com/alibaba/DeepRec/pull/291/files

**Comment by aalbersk** [comment]
> @aalbersk Please add api_def, like **FusedL2Normalize** in tensorflow/core/api_def/base_api/api_def_FusedL2Normalize.pbtxt from https://github.com/alibaba/DeepRec/pull/291/files

done

**Review by liutongxuan — APPROVED** [review]

**Comment by changqi1** [comment]
@aalbersk  The CI Build has an issue in compiling, please see the details: https://github.com/alibaba/DeepRec/pull/314/checks
image

**Review by liutongxuan — APPROVED** [review]

**Review by liutongxuan — APPROVED** [review]

**Comment by aalbersk** [comment]
> @aalbersk The CI Build has an issue in compiling, please see the details: https://github.com/alibaba/DeepRec/pull/314/checks image
> 
> Give you a tip, this is oneDNN patch for exposing some API: https://github.com/changqi1/DeepRec/blob/main/third_party/mkl_dnn/oneDNN-v2.3.2-expose-bf16-tp.patch Like gemm_bf16bf16f32: [changqi1/DeepRec-deprecated@2865ded#diff-064f747dfd4fd8e51fdc87b8df6012414c8735c64d72174edd11b6a8037c39d5R208-R232](https://github.com/changqi1/DeepRec-deprecated/commit/2865ded9ef6b25ff10e6ae36e6583a474a30cbf6#diff-064f747dfd4fd8e51fdc87b8df6012414c8735c64d72174edd11b6a8037c39d5R208-R232)
> 
> @marvin-Yu Do you have some comments?

fixed

**Comment by changqi1** [comment]
@liutongxuan  LGTM

**Comment by changqi1** [comment]
@aalbersk There is a bug in the main branch of merged your code. This issue is from GPU UT. So I think you need to enable the optimization only in the CPU path.

image

**Comment by aalbersk** [comment]
> @aalbersk There is a bug in the main branch of merged your code. This issue is from GPU UT. So I think you need to enable the optimization only in the CPU path.
> 
> image

Yes. The fix has been added: https://github.com/alibaba/DeepRec/pull/325

**Pull request merged**
